#!/bin/sh

# Set "toor" as user password
usermod -p 'X014elvznJq7E' user

#sed -i 's/AutomaticLogin/#AutomaticLogin/g' /etc/gdm3/daemon.conf
#sed -i 's/TimedLogin/#TimedLogin/g' /etc/gdm3/daemon.conf
